### PR TITLE
Chore: Fixes pep8 errors #147322149

### PR DESCRIPTION
**Pull request by daumie**
### What does this PR do?

Style the codebase to be inline with PEP8 guidelines.

### Description of task to be completed?

Shorten long lines to < 80 charcters
Add module doctrings
Add class docstrings
Add function and methods doctrings
Define variables before first use.
Fix syntax errors

#### How should this be manually tested?

Install `flake8` 
> pip install flake8

cd into the root directory of the project, then run:
> flake8

#### Relevantpivotal tracker stories covered

#147322149

### CODE REVIEW

**Review by egichuri — CHANGES_REQUESTED** [review]
Let's fix the merge conflict on this and check the failing tests

**Comment by egichuri** [comment]
@daumie lemme know if you are having any issues fixing the merge conflicts

**Comment by daumie** [comment]
@egichuri I have resolved the merge conflicts, the changed can be merged into *develop* branch.

**Comment by egichuri** [comment]
@daumie have you ran this branch locally?

**Comment by egichuri** [comment]
also run the tests locally before pushing the changes. there seems to be an issue with the way long lines in some `urls.py` are broken.

**Pull request closed without merging**
